@server = {{scheme}}://{{$processEnv COUCHDB_USER}}:{{$processEnv COUCHDB_PASSWORD}}@{{host}}
@database = test

### Deletes the database.
DELETE {{server}}/{{database}}
Accept: application/json

### Returns information about the database.
GET {{server}}/{{database}}
Accept: application/json

### Checks whether the database exists.
HEAD {{server}}/{{database}}
Accept: application/json

### Creates a new database.
PUT {{server}}/{{database}}
Accept: application/json

### Compacts the database.
POST {{server}}/{{database}}/_compact
Accept: application/json
Content-Type: application/json
