@server = {{scheme}}://{{$processEnv COUCHDB_USER}}:{{$processEnv COUCHDB_PASSWORD}}@{{host}}

### Returns information about the server.
GET {{server}}
Accept: application/json

### Returns the binary content for the `favicon.ico` site icon.
GET {{server}}/favicon.ico
Accept: image/x-icon

### Returns the list of active tasks.
GET {{server}}/_active_tasks
Accept: application/json

### Returns the list of all databases.
GET {{server}}/_all_dbs
Accept: application/json

### Displays the nodes that are part of the cluster.
GET {{server}}/_membership
Accept: application/json

### Returns a value indicating whether the server is up.
GET {{server}}/_up
Accept: application/json

### Requests one or more Universally Unique Identifiers (UUIDs) from the server.
GET {{server}}/_uuids?count=3
Accept: application/json
