@server = {{scheme}}://{{host}}
@cookie = cm9vdDo2NTVBNjczMzocQxD7MIBKt2FcWXX6XGA_TDNPK5G4uTBpXb6_fs2W9A

### Initiates a new session for the specified user credentials.
POST {{server}}/_session
Accept: application/json
Content-Type: application/json

{"name": "{{$processEnv COUCHDB_USER}}", "password": "{{$processEnv COUCHDB_PASSWORD}}"}

### Fetches information about the session.
GET {{server}}/_session
Accept: application/json

### Deletes the session.
DELETE {{server}}/_session
Accept: application/json
