@server = {{scheme}}://{{host}}
@cookie = cm9vdDo2NTRFNTNDNDpKYLNMkd0By3vPcUVCE7_59ASDLc4Qyy_b2EDtj22ldQ

### Initiates a new session for the specified user credentials.
POST {{server}}/_session
Accept: application/json
Content-Type: application/json

{"name": "{{$processEnv COUCHDB_USER}}", "password": "{{$processEnv COUCHDB_PASSWORD}}"}

### Fetches information about the session.
GET {{server}}/_session
Accept: application/json
Cookie: AuthSession={{cookie}}

### Deletes the session.
DELETE {{server}}/_session
Accept: application/json
Cookie: AuthSession={{cookie}}
